---
- name: Ensure unbound + rspamd are installed.
  package:
    name:
      - unbound
      - rspamd
      - wget
    state: present

- name: make the local server active by adding it to resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/network/config
    regexp: '^NETCONFIG\_DNS\_STATIC\_SERVERS'
    line: 'NETCONFIG_DNS_STATIC_SERVERS="::1"'

- name: enable automatic start of unbound
  ansible.builtin.systemd:
    enabled: yes
    masked: no
    name: unbound

- name: trigger regeneration of resolv.conf
  ansible.builtin.command: "netconfig update -f"

- name: create an unbound configuration file
  ansible.builtin.template:
    src: localsite.conf.j2
    dest: /etc/unbound/conf.d/localsite.conf
    owner: root
    group: unbound
    mode: '0644'

- name: get current root.key
  ansible.builtin.get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /etc/unbound/root.hints
    group: unbound
    mode: '0644'

- name: Add a monthly cron-job to keep it up-to-date
  ansible.builtin.cron:
    name: "unbound-root-hints"
    special_time: monthly
    state: present
    job: "sudo -u unbound wget https://www.internic.net/domain/named.cache -O /etc/unbound/root.hints"

- name: restart unbound
  ansible.builtin.systemd:
    state: restarted
    name: unbound

- name: set up rspamd redis connection
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/rspamd/local.d/redis.conf
    owner: root
    group: _rspamd
    mode: '0644'

- name: create logging configuration
  ansible.builtin.template:
    src: logging.inc.j2
    dest: /etc/rspamd/local.d/logging.inc
    owner: root
    group: _rspamd
    mode: '0644'

- name: create milter_headers
  ansible.builtin.template:
    src: milter_headers.conf.j2
    dest: /etc/rspamd/local.d/milter_headers.conf
    owner: root
    group: _rspamd
    mode: '0644'

- name: NOT IDEMPOTENT. set password of the rspamd web-interface.
  ansible.builtin.shell:  |
    echo password = \"$( rspamadm pw -p {{ rspamd_password }} )\"; >> /etc/rspamd/local.d/worker-controller.inc

- name: Configure whitelists and blacklists
  ansible.builtin.template:
    src: "{{item}}.j2"
    dest: "/etc/rspamd/local.d/{{item}}"
    owner: root
    group: _rspamd
    mode: '0644'
  loop:
    - multimap.conf
    - whitelist_ip.map
    - whitelist_from.map
    - blacklist_ip.map
    - blacklist_from.map

- name: set up rspamd Antivirus plugin to connect with clamav
  ansible.builtin.template:
    src: antivirus.conf.j2
    dest: /etc/rspamd/local.d/antivirus.conf
    owner: root
    group: _rspamd
    mode: '0644'

- name: create DKIM key directory
  ansible.builtin.file:
    path: /var/lib/rspamd/dkim
    state: directory
    owner: "{{ rspamd_user }}"
    group: "{{ rspamd_user }}"
    mode: '0755'

- name: Create DKIM key
  ansible.builtin.shell:  |
    rspamadm dkim_keygen -b {{ rspamd_dkim_key_length }} -s {{ rspamd_dkim_key_selector }} -k /var/lib/rspamd/dkim/{{ rspamd_dkim_key_selector }}.key > /var/lib/rspamd/dkim/{{ rspamd_dkim_key_selector }}.txt
    chown -R {{ rspamd_user }}:{{ rspamd_user }} /var/lib/rspamd/dkim
    chmod 440 /var/lib/rspamd/dkim/*

- name: set up rspamd dkim signing configuration
  ansible.builtin.template:
    src: "{{item}}.j2"
    dest: "/etc/rspamd/local.d/{{item}}"
    owner: root
    group: _rspamd
    mode: '0644'
  loop:
    - dkim_signing.conf
    - arc.conf

- name: Enable Autolearning in rspamd
  ansible.builtin.copy:
    dest: "/etc/rspamd/local.d/classifier-bayes.conf"
    owner: root
    group: _rspamd
    mode: '0644'
    content: |
      autolearn = true;

- name: adding "{{ rspamd_user }}" to group redis
  user:
    name: "{{ rspamd_user }}"
    groups: redis
    append: yes

- name: adding "{{ rspamd_user }}" to group vscan
  user:
    name: "{{ rspamd_user }}"
    groups: vscan
    append: yes

- name: restart rspamd
  ansible.builtin.systemd:
    state: restarted
    name: rspamd
